src/Entity/Gpn.php
<?php

namespace App\Entity;

use App\Repository\GpnRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=GpnRepository::class)
 */
class Gpn
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $civilite;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le champ Nom est obligatoire")
     * @Assert\Regex(
     *     pattern="/[A-Za-zéèêëàâîïôöûü-]+/",
     *     htmlPattern="/[A-Za-zéèêëàâîïôöûü-]+/",
     *     message="Le champ Nom ne peut contenir que des lettres")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le champ Prénom est obligatoire")
     * @Assert\Regex(
     *     pattern="/[A-Za-zéèêëàâîïôöûü-]+/",
     *     htmlPattern="/[A-Za-zéèêëàâîïôöûü-]+/",
     *     message="Le champ Prénom ne peut contenir que des lettres")
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=10)
     * @Assert\NotBlank(message="Le champ Téléphone est obligatoire")
     * @Assert\Length(
     *      min = 10,
     *      minMessage = "Le champ Téléphone doit contenir {{ limit }} caractères")
     * @Assert\Regex(
     *     pattern="/^[0]{1}[1-79]{1}[0-9]{8}$/",
     *     htmlPattern="/^[0]{1}[1-79]{1}[0-9]{8}$/",
     *     message="Votre numéro de téléphone doit être au format 0xxxxxxxxx")
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le champ Email est obligatoire")
     * @Assert\Email(message = "L'email '{{ value }}' est invalide.")
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Le champ Adresse est obligatoire")
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=5)
     * @Assert\NotBlank(message="Le champ Code postal est obligatoire")
     * @Assert\Length(
     *      min = 5,
     *      max = 5,
     *      minMessage = "Le champ Code postal doit contenir {{ limit }} chiffres",
     *      maxMessage = "Le champ Code postal doit contenir {{ limit }} chiffres")
     * @Assert\Regex(
     *     pattern="/^((0[1-9])|([1-8][0-9])|(9[0-8])|(2A)|(2B))*([0-9]{3})?$/",
     *     htmlPattern = "/^((0[1-9])|([1-8][0-9])|(9[0-8])|(2A)|(2B))*([0-9]{3})?$/",
     *     message="Le champ Code postal ne peut contenir que des chiffres")
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le champ Ville est obligatoire")
     * @Assert\Regex(
     *     pattern="/[A-Za-zéèêëàâîïôöûü-]+/",
     *     htmlPattern="/[A-Za-zéèêëàâîïôöûü-]+/",
     *     message="Le champ Ville ne peut contenir que des lettres")
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $raisonSociale;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nombreSalarie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fonction;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $adresseIP;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $optinGenerali;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $CA;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $eCommercant;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sourceClient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $codeCampagne;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $urlReferrer;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $tracking;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $canal;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $familleProduit;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $identifiantPartenaire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $produit;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $reseau;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $conqueteLeadTechnicalId;

    /**
     * @return mixed
     */
    public function getCodeCampagne()
    {
        return $this->codeCampagne;
    }

    /**
     * @param mixed $codeCampagne
     */
    public function setCodeCampagne($codeCampagne): void
    {
        $this->codeCampagne = $codeCampagne;
    }

    /**
     * @return mixed
     */
    public function getUrlReferrer()
    {
        return $this->urlReferrer;
    }

    /**
     * @param mixed $urlReferrer
     */
    public function setUrlReferrer($urlReferrer): void
    {
        $this->urlReferrer = $urlReferrer;
    }

    /**
     * @return mixed
     */
    public function getTracking()
    {
        return $this->tracking;
    }

    /**
     * @param mixed $tracking
     */
    public function setTracking($tracking): void
    {
        $this->tracking = $tracking;
    }

    /**
     * @return mixed
     */
    public function getProduit()
    {
        return $this->produit;
    }

    /**
     * @param mixed $produit
     */
    public function setProduit($produit): void
    {
        $this->produit = $produit;
    }

    /**
     * @return mixed
     */
    public function getSourceClient()
    {
        return $this->sourceClient;
    }

    /**
     * @param mixed $sourceClient
     */
    public function setSourceClient($sourceClient): void
    {
        $this->sourceClient = $sourceClient;
    }

    /**
     * @return mixed
     */
    public function getOptinGenerali()
    {
        return $this->optinGenerali;
    }

    /**
     * @param mixed $optinGenerali
     */
    public function setOptinGenerali($optinGenerali): void
    {
        $this->optinGenerali = $optinGenerali;
    }

    /**
     * @return mixed
     */
    public function getdate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setdate($date): void
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getAdresseIP()
    {
        return $this->adresseIP;
    }

    /**
     * @param mixed $adresseIP
     */
    public function setAdresseIP($adresseIP): void
    {
        $this->adresseIP = $adresseIP;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCpltAdresse(): ?string
    {
        return $this->cpltAdresse;
    }

    public function setCpltAdresse(string $cpltAdresse): self
    {
        $this->cpltAdresse = $cpltAdresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raisonSociale;
    }

    public function setRaisonSociale(string $raisonSociale): self
    {
        $this->raisonSociale = $raisonSociale;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getNombreSalarie(): ?int
    {
        return $this->nombreSalarie;
    }

    public function setNombreSalarie(?int $nombreSalarie): self
    {
        $this->nombreSalarie = $nombreSalarie;

        return $this;
    }

    public function getFonction(): ?string
    {
        return $this->fonction;
    }

    public function setFonction(?string $fonction): self
    {
        $this->fonction = $fonction;

        return $this;
    }

    public function getCA(): ?int
    {
        return $this->CA;
    }

    public function setCA(?int $CA): self
    {
        $this->CA = $CA;

        return $this;
    }

    public function getECommercant(): ?bool
    {
        return $this->eCommercant;
    }

    public function setECommercant(?bool $eCommercant): self
    {
        $this->eCommercant = $eCommercant;

        return $this;
    }

src/Entity/ListeForms.php
<?php

namespace App\Entity;

use App\Repository\ListeFormsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ListeFormsRepository::class)
 */
class ListeForms
{
    public function __toString()
    {
        return (string)$this->getNomFormulaire();
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomFormulaire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomProduit;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $UniversProduit;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateCreation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $urlFormulaire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $urlAdminFormulaire;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $visuelEntete;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logoProduit;

    /**
     * @return mixed
     */
    public function getLogoProduit()
    {
        return $this->logoProduit;
    }

    /**
     * @ORM\OneToMany(targetEntity=ArgumentProduit::class, mappedBy="idFormulaire")
     */
    private $argumentProduits;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pictoMenu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $campagne;

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @param mixed $logoProduit
     */
    public function setLogoProduit($logoProduit): void
    {
        $this->logoProduit = $logoProduit;
    }

    /**
     * @param ArrayCollection $argumentProduits
     */
    public function setArgumentProduits(ArrayCollection $argumentProduits): void
    {
        $this->argumentProduits = $argumentProduits;
    }

    /**
     * @param mixed $campagne
     */
    public function setCampagne($campagne): void
    {
        $this->campagne = $campagne;
    }

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tcFormName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tcFormNameMerci;

    /**
     * @return mixed
     */
    public function getTcFormNameMerci()
    {
        return $this->tcFormNameMerci;
    }

    /**
     * @param mixed $tcFormNameMerci
     */
    public function setTcFormNameMerci($tcFormNameMerci): void
    {
        $this->tcFormNameMerci = $tcFormNameMerci;
    }

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tcProductCategory;

    /**
     * @return mixed
     */
    public function getCampagne()
    {
        return $this->campagne;
    }

    public function __construct()
    {
        $this->argumentProduits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFormulaire(): ?string
    {
        return $this->NomFormulaire;
    }

    public function setNomFormulaire(string $NomFormulaire): self
    {
        $this->NomFormulaire = $NomFormulaire;

        return $this;
    }

    public function getNomProduit(): ?string
    {
        return $this->NomProduit;
    }

    public function setNomProduit(string $NomProduit): self
    {
        $this->NomProduit = $NomProduit;

        return $this;
    }

    public function getUniversProduit(): ?string
    {
        return $this->UniversProduit;
    }

    public function setUniversProduit(string $UniversProduit): self
    {
        $this->UniversProduit = $UniversProduit;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): self
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    public function getUrlFormulaire(): ?string
    {
        return $this->urlFormulaire;
    }

    public function setUrlFormulaire(string $urlFormulaire): self
    {
        $this->urlFormulaire = $urlFormulaire;

        return $this;
    }

    public function getUrlAdminFormulaire(): ?string
    {
        return $this->urlAdminFormulaire;
    }

    public function setUrlAdminFormulaire(string $urlAdminFormulaire): self
    {
        $this->urlAdminFormulaire = $urlAdminFormulaire;

        return $this;
    }

    public function getVisuelEntete(): ?string
    {
        return $this->visuelEntete;
    }

    public function setVisuelEntete(?string $visuelEntete): self
    {
        $this->visuelEntete = $visuelEntete;

        return $this;
    }

    /**
     * @return Collection|ArgumentProduit[]
     */
    public function getArgumentProduits(): Collection
    {
        return $this->argumentProduits;
    }

    public function addArgumentProduit(ArgumentProduit $argumentProduit): self
    {
        if (!$this->argumentProduits->contains($argumentProduit)) {
            $this->argumentProduits[] = $argumentProduit;
            $argumentProduit->setIdFormulaire($this);
        }

        return $this;
    }

    public function removeArgumentProduit(ArgumentProduit $argumentProduit): self
    {
        if ($this->argumentProduits->contains($argumentProduit)) {
            $this->argumentProduits->removeElement($argumentProduit);
            // set the owning side to null (unless already changed)
            if ($argumentProduit->getIdFormulaire() === $this) {
                $argumentProduit->setIdFormulaire(null);
            }
        }

        return $this;
    }

    public function getPictoMenu(): ?string
    {
        return $this->pictoMenu;
    }

    public function setPictoMenu(string $pictoMenu): self
    {
        $this->pictoMenu = $pictoMenu;

        return $this;
    }

    public function getTcFormName(): ?string
    {
        return $this->tcFormName;
    }

    public function setTcFormName(?string $tcFormName): self
    {
        $this->tcFormName = $tcFormName;

        return $this;
    }

    public function getTcProductCategory(): ?string
    {
        return $this->tcProductCategory;
    }

    public function setTcProductCategory(?string $tcProductCategory): self
    {
        $this->tcProductCategory = $tcProductCategory;

        return $this;
    }

}

templates/gpn/confirmation.html.twig
{% extends 'base.html.twig' %}
{% block body_class 'forGPN' %}
{% block boutonParticipation %}{% endblock %}
{% block visuelHeader %}
    <img src="{{ asset('build/images/produits/visuel-header-gpn.jpg') }}" alt="{{ options.nomProduit }}"
         class="img-fluid">
{% endblock %}
{% block cartouche %}{% endblock %}
{% block cartoucheMobile %}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12 py-3">
            <div class="card text-center py-3">
                <div class="card-body">
                    <p class="font-weight-bold text-center text-uppercase mt-4">
                        Nous vous remercions pour votre confiance.</p>
                    <p class="font-weight-bold text-center text-uppercase">Un agent Generali prendra contact avec vous
                        dans les plus brefs délais.</p>
                    {% if options.logoProduit is not empty %}
                        <img src="{{ asset(options.logoProduit) }}" alt="{{ options.nomProduit }}"
                             class="img-fluid img-size-logo">
                    {% endif %}
                </div>
                <p class="text-center text-blanc">Découvrez notre site <a href="https://www.generali.fr"
                                                                          target="_blank">https://www.generali.fr</a> ou
                    retrouvez nous sur les réseaux sociaux :</p>
                <p class="text-center text-blanc">
                <ul class="share-buttons text-center">
                    <li class="mt-2 mt-sm-0">
                        <a href="https://www.facebook.com/GeneraliFrance/" class="g-tracking-click"
                           title="Nous suivre sur Facebook" data-tracking-type="gaevent"
                           data-tag-label="Facebook"
                           data-tag-category="footer" data-tag-action="click" target="_blank"
                           onclick="javascript: return tc_events_5(this,'gaevent',{'category': 'footer_suivi_rs','action': 'click', 'label': 'facebook_generali_prevention', 'value': '1'})">
                            <img alt="Nous suivre sur Facebook" src="{{ asset('build/images/svg/facebook.svg') }}"/>
                        </a></li>
                    <li class="mt-2 mt-sm-0">
                        <a href="https://twitter.com/generalifrance" class="g-tracking-click"
                           title="Nous suivre sur Twitter" data-tracking-type="gaevent"
                           data-tag-label="Twitter"
                           data-tag-category="footer" data-tag-action="click" target="_blank"
                           onclick="javascript: return tc_events_5(this,'gaevent',{'category': 'footer_suivi_rs','action': 'click', 'label': 'twitter_generalifrance', 'value': '1'})">
                            <img alt="Nous suivre sur Twitter" src="{{ asset('build/images/svg/twitter.svg') }}"/>
                        </a></li>
                    <li class="mt-2 mt-sm-0">
                        <a href="https://www.linkedin.com/company/generali" class="g-tracking-click"
                           title="Nous suivre sur Linkedin" data-tracking-type="gaevent"
                           data-tag-label="Linkedin"
                           data-tag-category="footer" data-tag-action="click" target="_blank"
                           onclick="javascript: return tc_events_5(this,'gaevent',{'category': 'footer_suivi_rs','action': 'click', 'label': 'linkedin_generali', 'value': '1'})">
                            <img alt="Nous suivre sur Linkedin" src="{{ asset('build/images/svg/linkedin.svg') }}"/>
                        </a></li>
                    <li class="mt-2 mt-sm-0">
                        <a href="https://www.youtube.com/user/generalifrance" class="g-tracking-click"
                           title="Nous suivre sur Youtube" data-tracking-type="gaevent"
                           data-tag-label="Youtube"
                           data-tag-category="footer" data-tag-action="click" target="_blank"
                           onclick="javascript: return tc_events_5(this,'gaevent',{'category': 'footer_suivi_rs','action': 'click', 'label': 'youtube_generalifrance', 'value': '1'})">
                            <img alt="Nous suivre sur Youtube"
                                 src="{{ asset('build/images/svg/youtube_social_circle_red.png') }}"
                                 style="max-width: 40px"/>
                        </a></li>
                </ul>
                </p>
            </div>
        </div>
    </div>
{% endblock %}
{% block form_step %}'2'{% endblock form_step %}
{% block page_name %}'{{ options.tcFormNameMerci }}'{% endblock page_name %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('formulaire_front') }}
{% endblock %}

templates/gpn/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Generali Protection Numérique{% endblock %}
{% block body_class 'formGPN' %}
{% block visuelHeader %}
    <img src="{{ asset('build/images/produits/visuel-header-gpn.jpg') }}" alt="{{ options.nomProduit }}"
         class="img-fluid">
{% endblock %}
{% block formulaire %}
    <div class="row">
        <div class="col-12">
            {{ form_start(form, {'attr': {'novalidate': 'novalidate', 'class': 'needs-validation'}}) }}
            <div class="row">
                <div class="col-12 col-sm">
                    <p class="text-right mentions">
                        <span class="couleur-etoile">*</span> Champs obligatoires</p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 mb-2">
                    {{ form_label(form.civilite, 'Civilité') }}
                    {{ form_widget(form.civilite, {
                        'attr' : {'class' : 'lblCivilite'}
                    }) }}
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    {{ form_row(form.nom) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(form.prenom) }}
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    {{ form_row(form.telephone) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(form.email) }}
                </div>
            </div>

            <div class="mb-2">
                {{ form_row(form.adresse) }}
            </div>

            <div class="row" id="cpVille">
                <div class="col-md-4">
                    {{ form_row(form.cp) }}
                </div>
                <div class="col-md-8">
                    {{ form_row(form.ville) }}
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    {{ form_row(form.raisonSociale) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(form.nombreSalarie) }}
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    {{ form_row(form.cA) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(form.activite) }}
                </div>
            </div>

            <div class="mb-2">
                {{ form_row(form.fonction) }}
            </div>

            <div class="row py-2">
                <div class="col-12">
                    {{ form_label(form.eCommercant) }}
                    {{ form_widget(form.eCommercant, {
                        'attr' : {'class' : 'lblCivilite'}
                    }) }}
                </div>
            </div>

            <div class="row">
                <div class="col pt-2">
                    {{ form_row(form.optinGenerali) }}
                </div>
            </div>
            <p class="text-center">
                <button class="btn btn-outline-primary" type="submit"
                        onclick="return tc_events_5(this,'gaevent',{'category': 'accueil','action': 'click', 'label': 'valider_mon_inscription', 'value': '1'})">
                    <span>Je souhaite être rappelé(e)</span>
                </button>
            </p>
            <p class="mentions text-center">
                Vous trouverez les informations sur vos données personnelles<br>en
                <a role="button" class="link-primary" data-toggle="collapse" href="#cnil" aria-expanded="false"
                   aria-controls="collapseExample"
                   onclick="return tc_events_5(this,'gaevent',{'category': 'formulaire','action': 'clic', 'label': 'texte_donnees_perso', 'value': '1'})">
                    <span class="text-gras">suivant ce lien</span>.
                </a>
            </p>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('formulaire_front') }}
{% endblock %}